channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - dill==0.3.9
  - numpy==2.1.2
  - pandas==2.2.3
  - torch==2.4.1
name: mlflow-env
